### PR TITLE
Various cleanup and formatting

### PR DESCRIPTION
**Pull request by JensRantil**
See individual commits for the exact changes. No logic modified.

### CODE REVIEW

**Comment by JensRantil** [comment]
Hello, any input on this please?

**Comment by JensRantil** [comment]
@patedit FYI, I just fixed merge conflicts here. Let me know if I can do anything here.

**Comment by JensRantil** [comment]
@patedit Fixed merge conflicts once again.

**Comment by patedit** [comment]
Thanks

**Pull request merged**
